const httpCode = code =>
  ({
    "0": "Network Error",
    "100": "Information: Continue",
    "101": "Information: Switching Protocols",
    "102": "Information: Processing",
    "200": "Success: OK",
    "201": "Success: Created",
    "202": "Success: Accepted",
    "203": "Success: Non-Authoritative Information",
    "204": "Success: No Content",
    "205": "Success: Reset Content",
    "206": "Success: Partial Content",
    "207": "Success: Multi-Status",
    "208": "Success: Multi-Status",
    "226": "Success: IM Used",
    "300": "Redirect: Multiple Choices",
    "301": "Redirect: Moved Permanently",
    "302": "Redirect: Found",
    "303": "Redirect: See Other",
    "304": "Redirect: Not Modified",
    "307": "Redirect: Temporary Redirect",
    "308": "Redirect: Permanent Redirect",
    "400": "Error: Bad Request",
    "401": "Error: Unauthorized",
    "402": "Error: Payment Required",
    "403": "Error: Forbidden",
    "404": "Error: Not Found",
    "405": "Error: Method Not Allowed",
    "406": "Error: Not Acceptable",
    "407": "Error: Proxy Authentication Required",
    "408": "Error: Request Timeout",
    "409": "Error: Conflict",
    "410": "Error: Gone",
    "411": "Error: Length Required",
    "412": "Error: Precondition Failed",
    "413": "Error: Payload Too Large",
    "414": "Error: URI Too Long",
    "415": "Error: Unsupported Media Type",
    "416": "Error: Range Not Satisfiable",
    "417": "Error: Expectation Failed",
    "418": "Error: I'm a teapot",
    "421": "Error: Misdirected Request",
    "422": "Error: Unprocessable Entity",
    "423": "Error: Locked",
    "424": "Error: Failed Dependency",
    "426": "Error: Upgrade Required",
    "428": "Error: Precondition Required",
    "429": "Error: Too Many Requests",
    "431": "Error: Request Header Fields Too Large",
    "451": "Error: Unavailable For Legal Reasons",
    "500": "Server Error: Internal Server Error",
    "501": "Server Error: Not Implemented",
    "502": "Server Error: Bad Gateway",
    "503": "Server Error: Service Unavailable",
    "504": "Server Error: Gateway Timeout",
    "505": "Server Error: HTTP Version Not Supported",
    "506": "Server Error: Variant Also Negotiates",
    "507": "Server Error: Insufficient Storage",
    "508": "Server Error: Loop Detected",
    "508": "Server Error: Not Extended",
    "511": "Server Error: Network Authentication Required"
  }[code]);

export { httpCode };
